version: '3.7'

services:
  boardwe-database:
    container_name: db
    image: wjyddd/boardwe-db:prod
    ports:
      - 3306:3306
    volumes:
      -  boardwe_db_volume:/var/lib/mysql

volumes:
  boardwe_db_volume: