server:
  port: 16383

spring:
  datasource:
    username: boardwe
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    org.hibernate.SQL: info
    #    org.hibernate.type: trace
    root: info

file:
  upload-dir: ./files

board-we:
  file-server: localhost:16383

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/boardwe?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul

logging:
  level:
    org.hibernate.SQL: debug
    config: classpath:log4j2-dev.xml

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

logging:
  config: classpath:log4j2-prod.xml