#server:
#  port: 16383

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/boardWe
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true # sout?? ??
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    #    org.hibernate.type: trace

file:
  upload-dir: ./files