server:
  servlet:
    session:
      timeout: 300
  port: 16383

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardwe?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: boardwe
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    org.hibernate.SQL: info
    #    org.hibernate.type: trace
    root: info

file:
  upload-dir: ./files

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    stack:
      -auto: false
    s3:
      bucket: board-me
    region:
      static: