version: '3.7'

services:
  boardwe-database:
    container_name: db2
    image: wjyddd/boardwe-database:local-test
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      -  boardwe_db_volume:/var/lib/mysql
  boardwe-backend:
    container_name: backend2
    image: boardwe-backend:hyunwoo
    ports:
      - 16383:16383
    environment:
      DB_HOSTNAME: boardwe-database
      DB_PORT: 3306
      FILE_SERVER: localhost:16383
    restart: always
    volumes:
      - boardwe_shared_volume:/boardwe_home
    depends_on:
      - boardwe-database

volumes:
  boardwe_db_volume:
  boardwe_shared_volume:
