version: '3.7'

services:
  boardwe-database:
    container_name: db
    image: wjyddd/boardwe-database:v0.1.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      -  boardwe_db_volume:/var/lib/mysql

volumes:
  boardwe_db_volume: